arch-wrpc: avoid needless compilation and better error message
The existing rule to check whether WRPCSW_ROOT is properly set (by
environment or default in Kconfig) forced a dependency on all object
file.  Thus, all files were rebuilt every time.

We now force the check only as a dependency for the first object file,
which means ony fsm.o (and then ppsi.o) is built if you run "make" on
a just-built source tree.

Signed-off-by: Alessandro Rubini <rubini@gnudd.com>

diff --git a/arch-wrpc/Makefile b/arch-wrpc/Makefile
--- a/arch-wrpc/Makefile
+++ b/arch-wrpc/Makefile
@@ -31,10 +31,11 @@ include time-wrpc/Makefile
 
 $(TARGET).o: $(LIBARCH)
 
-$(OBJ-y): wrpcsw_root_check
+fsm.o: wrpcsw_root_check
 
 wrpcsw_root_check:
-	if ! [ -e "$(WRPCSW_ROOT)/include/wrc.h" ]; then\
-		echo "Error: WRPCSW_ROOT: can't find $(WRPCSW_ROOT)/include/wrc.h" >&2;\
+	@if ! [ -e "$(WRPCSW_ROOT)/include/wrc.h" ]; then\
+		echo "Error:  can't find $(WRPCSW_ROOT)/include/wrc.h" >&2; \
+		echo "  please set WRPCSW_ROOT in your environment" >&2; \
 		exit 1;\
 	fi
